name: "Slideshow Server"
url: "https://github.com/msherga/python-http-slideshow/"
version: "1.2"
slug: "slideshow_http"
description: "Serves /config/www/Slideshow via HTTP"
startup: application
boot: auto
host_network: true
map:
  - config:rw
  - media:rw
init: false
panel_icon: mdi:image
arch:
  - amd64
  - aarch64
  - armv7
